# 03 - Aggrega e raggruppa

## Sezione 1: Warm up

In [3]:
import pandas as pd

In [4]:
titanic = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [5]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
titanic["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [7]:
titanic["Sex"].value_counts(normalize=True)

Sex
male      0.647587
female    0.352413
Name: proportion, dtype: float64

In [8]:
titanic["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

## Sezione 2: Groupby

In [9]:
titanic.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [10]:
titanic.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [11]:
titanic.groupby(["Pclass", "Sex"])["Survived"].mean()

Pclass  Sex
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: Survived, dtype: float64

In [12]:
titanic.groupby("Pclass")["Age"].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

## Sezione 3: .agg()

In [13]:
titanic.groupby("Pclass")["Age"].agg(["mean", "median", "std"])

             mean  median        std
Pclass
1       38.233441    37.0  14.802856
2       29.877630    29.0  14.001077
3       25.140620    24.0  12.495398

In [14]:
titanic.groupby(["Pclass", "Sex"]).agg(
    eta_media=("Age", "mean"), 
    fare_medio=("Fare", "mean"), 
    sopravvissuti=("Survived", "sum"),
    totale=("Survived", "size"))

               eta_media  fare_medio  sopravvissuti  totale
Pclass Sex
1      female  34.611765  106.125798             91      94
       male    41.281386   67.226127             45     122
2      female  28.722973   21.970121             70      76
       male    30.740707   19.741782             17     108
3      female  21.750000   16.118810             72     144
       male    26.507589   12.661633             47     347

In [15]:
titanic.groupby(["Pclass", "Sex"])["Age"].mean()

Pclass  Sex
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: Age, dtype: float64

## Sezione 4: Esercizi di ripasso

In [16]:
titanic.groupby("Sex")[["Age", "Fare"]].mean()

              Age       Fare
Sex
female  27.915709  44.479818
male    30.726645  25.523893

In [17]:
titanic.groupby(["Pclass", "Embarked"]).size()

Pclass  Embarked
1       C            85
        Q             2
        S           127
2       C            17
        Q             3
        S           164
3       C            66
        Q            72
        S           353
dtype: int64

In [18]:
titanic.groupby("Sex").agg(eta_media=("Age", "mean"))

        eta_media
Sex
female  27.915709
male    30.726645