# 03 - Aggrega e raggruppa

## Sezione 1: Warm up

In [8]:
import pandas as pd

In [9]:
titanic = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [10]:
titanic["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [37]:
titanic["Sex"].value_counts(normalize=True)

Sex
male      0.647587
female    0.352413
Name: proportion, dtype: float64

In [34]:
titanic["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

## Sezione 2: Groupby

In [15]:
titanic.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [16]:
titanic.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [17]:
titanic.groupby(["Pclass", "Sex"])["Survived"].mean()

Pclass  Sex
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: Survived, dtype: float64

In [19]:
titanic.groupby("Pclass")["Age"].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

## Sezione 3: .agg()

In [20]:
titanic.groupby("Pclass")["Age"].agg(["mean", "median", "std"])

             mean  median        std
Pclass
1       38.233441    37.0  14.802856
2       29.877630    29.0  14.001077
3       25.140620    24.0  12.495398

In [31]:
titanic.groupby(["Pclass", "Sex"]).agg(
    eta_media=("Age", "mean"), 
    fare_medio=("Fare", "mean"), 
    sopravvissuti=("Survived", "sum"),
    totale=("Survived", "size"))

               eta_media  fare_medio  sopravvissuti  totale
Pclass Sex
1      female  34.611765  106.125798             91      94
       male    41.281386   67.226127             45     122
2      female  28.722973   21.970121             70      76
       male    30.740707   19.741782             17     108
3      female  21.750000   16.118810             72     144
       male    26.507589   12.661633             47     347

In [38]:
titanic.groupby(["Pclass", "Sex"])["Age"].mean()

Pclass  Sex
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: Age, dtype: float64

## Sezione 4: Esercizi di ripasso